### ISSUE TITLE
[Request] Support for MacOS Sierra (probably El Capitan too)

### ISSUE THREAD

**Issue by bbbenji** [svg/svgo-osx-folder-action#5]
Unable to install the action on MacOS Sierra. Returns error:

`osacompile: OpenScripting.framework - scripting addition "/Library/ScriptingAdditions/QXPScriptingAdditions.osax" cannot be used with the current OS because it has no OSAXHandlers entry in its Info.plist.`

**Comment by secretholding** [comment]
This error is thrown because of an old QuarkXPress AppleScript extension in your scripting additions folder. I read a forum post that mentioned this was installed with version 7 of QXP.

The extension in question is legacy software and it is very doubtful Quark will be updating it to fix the error you are getting.

If you no longer use QXP or are using a new version of it, you can safely remove this extension from the /Library/ScriptingAdditions folder and you should no longer get the error.
